/**
 * BANCO DE VOCABULARIO CEFR (A1 → C2) — curado para el modo Battle 2.0 y futuros modos.
 *
 * Cada palabra: inglés, traducción al español y una pista de pronunciación legible
 * para hispanohablantes (la pronunciación real la da el audio TTS). Las palabras están
 * planificadas por nivel para un aprendizaje ordenado y NO se repiten dentro del banco.
 */
import type { CEFRLevel } from "@/lib/supabase/database.types";

export interface VocabWord {
  en: string;
  es: string;
  pron: string; // aproximación fonética para mostrar
}

export const VOCABULARY: Record<CEFRLevel, VocabWord[]> = {
  A1: [
    { en: "dog", es: "perro", pron: "dog" },
    { en: "cat", es: "gato", pron: "cat" },
    { en: "house", es: "casa", pron: "jaus" },
    { en: "water", es: "agua", pron: "uóter" },
    { en: "milk", es: "leche", pron: "milk" },
    { en: "apple", es: "manzana", pron: "ápol" },
    { en: "bread", es: "pan", pron: "bred" },
    { en: "book", es: "libro", pron: "buk" },
    { en: "table", es: "mesa", pron: "téibol" },
    { en: "chair", es: "silla", pron: "cher" },
    { en: "school", es: "escuela", pron: "skuul" },
    { en: "friend", es: "amigo", pron: "frend" },
    { en: "red", es: "rojo", pron: "red" },
    { en: "blue", es: "azul", pron: "blu" },
    { en: "big", es: "grande", pron: "big" },
    { en: "small", es: "pequeño", pron: "smol" },
    { en: "happy", es: "feliz", pron: "jápi" },
    { en: "sun", es: "sol", pron: "san" },
    { en: "hand", es: "mano", pron: "jand" },
    { en: "day", es: "día", pron: "déi" },
    { en: "egg", es: "huevo", pron: "eg" },
    { en: "fish", es: "pez", pron: "fish" },
    { en: "bird", es: "pájaro", pron: "berd" },
    { en: "hat", es: "sombrero", pron: "jat" },
    { en: "shoe", es: "zapato", pron: "shu" },
    { en: "shirt", es: "camisa", pron: "shert" },
    { en: "ball", es: "pelota", pron: "bol" },
    { en: "door", es: "puerta", pron: "dor" },
    { en: "window", es: "ventana", pron: "uíndou" },
    { en: "tree", es: "árbol", pron: "trii" },
    { en: "star", es: "estrella", pron: "star" },
    { en: "moon", es: "luna", pron: "muun" },
    { en: "rain", es: "lluvia", pron: "réin" },
    { en: "snow", es: "nieve", pron: "snou" },
    { en: "green", es: "verde", pron: "griin" },
    { en: "black", es: "negro", pron: "blak" },
    { en: "white", es: "blanco", pron: "uáit" },
    { en: "cold", es: "frío", pron: "could" },
    { en: "hot", es: "caliente", pron: "jot" },
    { en: "boy", es: "niño", pron: "boi" },
    { en: "girl", es: "niña", pron: "guerl" },
  ],
  A2: [
    { en: "kitchen", es: "cocina", pron: "kítchen" },
    { en: "breakfast", es: "desayuno", pron: "brékfast" },
    { en: "weather", es: "clima", pron: "uéder" },
    { en: "holiday", es: "vacaciones", pron: "jólidei" },
    { en: "ticket", es: "boleto", pron: "tíket" },
    { en: "money", es: "dinero", pron: "máni" },
    { en: "market", es: "mercado", pron: "márket" },
    { en: "doctor", es: "médico", pron: "dóctor" },
    { en: "letter", es: "carta", pron: "léter" },
    { en: "music", es: "música", pron: "miúsik" },
    { en: "garden", es: "jardín", pron: "gárden" },
    { en: "river", es: "río", pron: "ríver" },
    { en: "bridge", es: "puente", pron: "brich" },
    { en: "mountain", es: "montaña", pron: "máunten" },
    { en: "key", es: "llave", pron: "kii" },
    { en: "clock", es: "reloj", pron: "clok" },
    { en: "neighbor", es: "vecino", pron: "néibor" },
    { en: "language", es: "idioma", pron: "lángüich" },
    { en: "story", es: "cuento", pron: "stóri" },
    { en: "pocket", es: "bolsillo", pron: "póket" },
    { en: "airport", es: "aeropuerto", pron: "érport" },
    { en: "station", es: "estación", pron: "stéichon" },
    { en: "hospital", es: "hospital", pron: "jóspital" },
    { en: "library", es: "biblioteca", pron: "láibreri" },
    { en: "beach", es: "playa", pron: "biich" },
    { en: "forest", es: "bosque", pron: "fórest" },
    { en: "island", es: "isla", pron: "áiland" },
    { en: "village", es: "pueblo", pron: "víllach" },
    { en: "machine", es: "máquina", pron: "mashíin" },
    { en: "factory", es: "fábrica", pron: "fáktori" },
    { en: "corner", es: "esquina", pron: "kórner" },
    { en: "floor", es: "piso", pron: "flor" },
    { en: "wall", es: "pared", pron: "uól" },
    { en: "roof", es: "techo", pron: "ruf" },
    { en: "gate", es: "portón", pron: "guéit" },
    { en: "path", es: "sendero", pron: "paz" },
    { en: "field", es: "campo", pron: "fíild" },
    { en: "voice", es: "voz", pron: "vois" },
    { en: "noise", es: "ruido", pron: "nois" },
    { en: "future", es: "futuro", pron: "fiúchur" },
  ],
  B1: [
    { en: "journey", es: "viaje", pron: "yérni" },
    { en: "decision", es: "decisión", pron: "disíchon" },
    { en: "advice", es: "consejo", pron: "adváis" },
    { en: "opinion", es: "opinión", pron: "opínion" },
    { en: "experience", es: "experiencia", pron: "ikspírians" },
    { en: "behavior", es: "comportamiento", pron: "bijéivior" },
    { en: "environment", es: "medioambiente", pron: "enváironment" },
    { en: "knowledge", es: "conocimiento", pron: "nólich" },
    { en: "success", es: "éxito", pron: "saksés" },
    { en: "failure", es: "fracaso", pron: "féilyur" },
    { en: "challenge", es: "desafío", pron: "chálench" },
    { en: "opportunity", es: "oportunidad", pron: "oportiúniti" },
    { en: "skill", es: "habilidad", pron: "skil" },
    { en: "goal", es: "meta", pron: "goul" },
    { en: "habit", es: "hábito", pron: "jábit" },
    { en: "mood", es: "ánimo", pron: "muud" },
    { en: "crowd", es: "multitud", pron: "kraud" },
    { en: "budget", es: "presupuesto", pron: "báyet" },
    { en: "deadline", es: "fecha límite", pron: "dédlain" },
    { en: "audience", es: "público", pron: "ódiens" },
    { en: "attitude", es: "actitud", pron: "átitiud" },
    { en: "confidence", es: "confianza", pron: "cónfidens" },
    { en: "pressure", es: "presión", pron: "préshur" },
    { en: "progress", es: "progreso", pron: "prógres" },
    { en: "purpose", es: "propósito", pron: "pérpos" },
    { en: "reaction", es: "reacción", pron: "riákchon" },
    { en: "relationship", es: "relación", pron: "riléichonship" },
    { en: "reputation", es: "reputación", pron: "repiutéichon" },
    { en: "responsibility", es: "responsabilidad", pron: "risponsabíliti" },
    { en: "routine", es: "rutina", pron: "rutíin" },
    { en: "solution", es: "solución", pron: "solúchon" },
    { en: "strength", es: "fortaleza", pron: "strengz" },
    { en: "weakness", es: "debilidad", pron: "uíknes" },
    { en: "benefit", es: "beneficio", pron: "bénefit" },
    { en: "balance", es: "equilibrio", pron: "bálans" },
    { en: "comfort", es: "comodidad", pron: "kómfort" },
    { en: "courage", es: "valentía", pron: "kérach" },
    { en: "curiosity", es: "curiosidad", pron: "kiuriósiti" },
    { en: "freedom", es: "libertad", pron: "fríidom" },
    { en: "pride", es: "orgullo", pron: "práid" },
  ],
  B2: [
    { en: "achievement", es: "logro", pron: "achívment" },
    { en: "assumption", es: "suposición", pron: "asámpchon" },
    { en: "consequence", es: "consecuencia", pron: "cónsicuens" },
    { en: "efficiency", es: "eficiencia", pron: "efíchensi" },
    { en: "framework", es: "marco", pron: "fréimuork" },
    { en: "hypothesis", es: "hipótesis", pron: "jaipózesis" },
    { en: "incentive", es: "incentivo", pron: "inséntiv" },
    { en: "leverage", es: "influencia", pron: "léverach" },
    { en: "negotiation", es: "negociación", pron: "nigochiéichon" },
    { en: "perception", es: "percepción", pron: "persépchon" },
    { en: "reliability", es: "fiabilidad", pron: "rilaiabíliti" },
    { en: "scope", es: "alcance", pron: "skoup" },
    { en: "threshold", es: "umbral", pron: "zréshold" },
    { en: "transparency", es: "transparencia", pron: "transpárensi" },
    { en: "trend", es: "tendencia", pron: "trend" },
    { en: "willingness", es: "disposición", pron: "uílingnes" },
    { en: "drawback", es: "inconveniente", pron: "dróbak" },
    { en: "breakthrough", es: "avance", pron: "bréikzru" },
    { en: "controversy", es: "controversia", pron: "cóntroversi" },
    { en: "insight", es: "perspicacia", pron: "ínsait" },
    { en: "accountability", es: "rendición de cuentas", pron: "akauntabíliti" },
    { en: "adversity", es: "adversidad", pron: "advérsiti" },
    { en: "alignment", es: "alineación", pron: "aláinment" },
    { en: "aspiration", es: "aspiración", pron: "aspiréichon" },
    { en: "bias", es: "sesgo", pron: "báias" },
    { en: "compromise", es: "acuerdo mutuo", pron: "cómpromais" },
    { en: "constraint", es: "restricción", pron: "constréint" },
    { en: "credibility", es: "credibilidad", pron: "credibíliti" },
    { en: "discipline", es: "disciplina", pron: "dísiplin" },
    { en: "empathy", es: "empatía", pron: "émpazi" },
    { en: "expertise", es: "pericia", pron: "ekspertíis" },
    { en: "foresight", es: "previsión", pron: "fórsait" },
    { en: "integrity", es: "integridad", pron: "intégriti" },
    { en: "momentum", es: "impulso", pron: "moméntum" },
    { en: "outcome", es: "resultado", pron: "áutcam" },
    { en: "paradox", es: "paradoja", pron: "páradoks" },
    { en: "precedent", es: "precedente", pron: "présedent" },
    { en: "rigor", es: "rigor", pron: "rígor" },
    { en: "sustainability", es: "sostenibilidad", pron: "sasteinabíliti" },
    { en: "turnover", es: "rotación", pron: "térnover" },
  ],
  C1: [
    { en: "ambiguity", es: "ambigüedad", pron: "ambigiúiti" },
    { en: "coherence", es: "coherencia", pron: "cojírens" },
    { en: "compliance", es: "cumplimiento", pron: "compláians" },
    { en: "discrepancy", es: "discrepancia", pron: "discrépansi" },
    { en: "endeavor", es: "empeño", pron: "endévor" },
    { en: "feasibility", es: "factibilidad", pron: "fizibíliti" },
    { en: "implication", es: "implicación", pron: "implikéichon" },
    { en: "nuance", es: "matiz", pron: "niúans" },
    { en: "paradigm", es: "paradigma", pron: "páradaim" },
    { en: "premise", es: "premisa", pron: "prémis" },
    { en: "prevalence", es: "prevalencia", pron: "prévalens" },
    { en: "rationale", es: "fundamento", pron: "rashonál" },
    { en: "resilience", es: "resiliencia", pron: "rizílians" },
    { en: "scrutiny", es: "escrutinio", pron: "scrútini" },
    { en: "stance", es: "postura", pron: "stans" },
    { en: "viability", es: "viabilidad", pron: "vaiabíliti" },
    { en: "versatility", es: "versatilidad", pron: "versatíliti" },
    { en: "undertaking", es: "tarea/empresa", pron: "andertéiking" },
    { en: "discretion", es: "discreción", pron: "discréchon" },
    { en: "consensus", es: "consenso", pron: "consénsus" },
    { en: "aftermath", es: "secuelas", pron: "áftermaz" },
    { en: "caveat", es: "advertencia", pron: "káviat" },
    { en: "conjecture", es: "conjetura", pron: "conyékchur" },
    { en: "deterrent", es: "disuasivo", pron: "ditérrent" },
    { en: "dichotomy", es: "dicotomía", pron: "daikótomi" },
    { en: "equilibrium", es: "equilibrio", pron: "ikuilíbrium" },
    { en: "hindrance", es: "obstáculo", pron: "jíndrans" },
    { en: "inception", es: "inicio", pron: "insépchon" },
    { en: "juncture", es: "coyuntura", pron: "yánkchur" },
    { en: "leniency", es: "indulgencia", pron: "líiniensi" },
    { en: "mitigation", es: "mitigación", pron: "mitiguéichon" },
    { en: "prerequisite", es: "requisito previo", pron: "prirékuisit" },
    { en: "proximity", es: "cercanía", pron: "proksímiti" },
    { en: "ramification", es: "ramificación", pron: "ramifikéichon" },
    { en: "salience", es: "relevancia", pron: "séilians" },
    { en: "surveillance", es: "vigilancia", pron: "servéilans" },
    { en: "tenet", es: "principio", pron: "ténet" },
    { en: "trajectory", es: "trayectoria", pron: "trayéktori" },
    { en: "validity", es: "validez", pron: "validíti" },
    { en: "vigilance", es: "vigilancia atenta", pron: "víyilans" },
  ],
  C2: [
    { en: "astuteness", es: "astucia", pron: "astiútnes" },
    { en: "connotation", es: "connotación", pron: "conotéichon" },
    { en: "deference", es: "deferencia", pron: "déferens" },
    { en: "eloquence", es: "elocuencia", pron: "élocuens" },
    { en: "idiosyncrasy", es: "idiosincrasia", pron: "idiosíncrasi" },
    { en: "juxtaposition", es: "yuxtaposición", pron: "yakstaposíchon" },
    { en: "meticulousness", es: "meticulosidad", pron: "metíkiulosnes" },
    { en: "ostentation", es: "ostentación", pron: "ostentéichon" },
    { en: "pragmatism", es: "pragmatismo", pron: "prágmatism" },
    { en: "propensity", es: "propensión", pron: "propénsiti" },
    { en: "quintessence", es: "quintaesencia", pron: "kuintésens" },
    { en: "redundancy", es: "redundancia", pron: "ridándansi" },
    { en: "sagacity", es: "sagacidad", pron: "sagásiti" },
    { en: "subtlety", es: "sutileza", pron: "sátlti" },
    { en: "tenacity", es: "tenacidad", pron: "tenásiti" },
    { en: "ubiquity", es: "ubicuidad", pron: "iubíkuiti" },
    { en: "vindication", es: "reivindicación", pron: "vindikéichon" },
    { en: "zeal", es: "fervor", pron: "ziil" },
    { en: "candor", es: "franqueza", pron: "cándor" },
    { en: "prudence", es: "prudencia", pron: "prúdens" },
    { en: "ambivalence", es: "ambivalencia", pron: "ambívalens" },
    { en: "brevity", es: "brevedad", pron: "bréviti" },
    { en: "cogency", es: "contundencia", pron: "kóuyensi" },
    { en: "demeanor", es: "comportamiento", pron: "dimíinor" },
    { en: "equanimity", es: "ecuanimidad", pron: "ekuanímiti" },
    { en: "hubris", es: "soberbia", pron: "jiúbris" },
    { en: "impetus", es: "ímpetu", pron: "ímpetus" },
    { en: "magnanimity", es: "magnanimidad", pron: "magnanímiti" },
    { en: "nonchalance", es: "indiferencia", pron: "nónchalans" },
    { en: "obfuscation", es: "ofuscación", pron: "obfaskéichon" },
    { en: "perspicacity", es: "perspicacia", pron: "perspikásiti" },
    { en: "rhetoric", es: "retórica", pron: "rétorik" },
    { en: "serendipity", es: "serendipia", pron: "serendípiti" },
    { en: "solemnity", es: "solemnidad", pron: "solémniti" },
    { en: "verisimilitude", es: "verosimilitud", pron: "verisimílitud" },
    { en: "wariness", es: "cautela", pron: "uérines" },
    { en: "zenith", es: "cénit", pron: "zéniz" },
    { en: "discernment", es: "discernimiento", pron: "disérnment" },
  ],
};

export interface BattleWord extends VocabWord {
  /** 4 opciones en español (una correcta), ya barajadas. */
  options: string[];
}

function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

/** Devuelve las palabras del nivel (con fallback a A1 si está vacío). */
export function wordsForLevel(level: CEFRLevel): VocabWord[] {
  return VOCABULARY[level]?.length ? VOCABULARY[level] : VOCABULARY.A1;
}

/**
 * Construye una sesión de Battle: `count` palabras del nivel, cada una con 4 opciones
 * en español (1 correcta + 3 distractores del mismo nivel), barajadas para que la
 * respuesta correcta caiga en distinta posición cada vez.
 */
export function buildBattleSession(level: CEFRLevel, count = 12): BattleWord[] {
  const pool = wordsForLevel(level);
  const chosen = shuffle(pool).slice(0, Math.min(count, pool.length));
  return chosen.map((w) => {
    const distractors = shuffle(pool.filter((x) => x.es !== w.es))
      .slice(0, 3)
      .map((x) => x.es);
    return { ...w, options: shuffle([w.es, ...distractors]) };
  });
}
